#Windows Template.yaml
AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Extract Predict Part 1 - File Server resource deployment
        Parameters:
          - KeyName
          - VPC
          - Subnet
          - SecurityGroupIds
          - LatestWindowsAmiId

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: A dropdown list enabling the selecting the key pair used to decrypt the Windows instance.

  VPC:
    Type: AWS::EC2::VPC::Id
    Description: A dropdown list enabling the selection of the Id for the VPC.

  Subnet:
    Type: AWS::EC2::Subnet::Id
    Description: A dropdown list enabling the selection of the Id for the public subnet created

  SecurityGroupIds:
    Type: AWS::EC2::SecurityGroup::Id
    Description: A multi-selection list enabling the selection of one or more security groups

  LatestWindowsAmiId:
    Description: A string-based resource path representing the latest Windows Amazon Machine Image
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id
    Default: /aws/service/ami-windows-latest/Windows_Server-2019-English-Full-Base

Resources:
  WindowsInstanceRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"

  WindowsInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: 
        - !Ref WindowsInstanceRole

  WindowsInstanceRolePolicy:
    Type: AWS::IAM::Policy
    DeletionPolicy: Delete
    Properties:
      PolicyName: Windows-client-DEDANOPA-WindowsStack    # Rememeber to name stack as this
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 's3:Get*'
              - 's3:List*'
            Resource: '*'
      Roles:
      - !Ref WindowsInstanceRole

  WindowsInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestWindowsAmiId
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref SecurityGroupIds
      SubnetId: !Ref Subnet
      IamInstanceProfile: !Ref WindowsInstanceProfile
      Tags:
        - Key: Name
          Value: "DE-Extract-Windows-Instance"
